"$schema" = 'https://starship.rs/config-schema.json'

format = '''
[░▒▓](color3)[󰣇](fg:#090c0c bg:color3)$username[](bg:color1 fg:color3)$directory[](fg:color1 bg:color2)$git_branch$git_status[](fg:color2 bg:color2)$nodejs$rust$golang$php[](fg:color2 bg:color0)$conda[ ](fg:color0)$line_break$character'''

palette = 'colors'

[palettes.colors]
mustard = '#af8700' # example
matugen-color1 = '{{colors.primary_fixed_dim.default.hex}}'
matugen-color2 = '{{colors.on_primary.default.hex}}'
matugen-color3 = '{{colors.on_surface_variant.default.hex}}'
matugen-color4 = '{{colors.surface_container.default.hex}}'
matugen-color5 = '{{colors.on_primary.default.hex}}'
matugen-color6 = '{{colors.on_primary.default.hex}}'
matugen-color7 = '{{colors.surface.default.hex}}'
matugen-color8 = '{{colors.primary.default.hex}}'
matugen-color9 = '{{colors.tertiary.default.hex}}'
matugen-color10 = '{{colors.on_primary_fixed.default.hex}}'
matugen-color11 = '{{colors.primary_container.default.hex}}'
matugen-color12 = '{{colors.on_secondary.default.hex}}'
color0 = 'black'
color1 = 'red'
color2 = 'green'
color3 = 'yellow'
color4 = 'blue'
color5 = 'magenta'
color6 = 'cyan'
color7 = 'white'
color8 = '#8bd5b5'
color9 = '#a6cce0'
color10 = '#002115'
color11 = '#00513a'
color12 = '#1f352b'


[username]
show_always = true
style_user = "fg:#090c0c bg:color3 "
style_root = "fg:#090c0c bg:color3 "
format = "[ $user ]($style)"
disabled = false


[directory]
style = "fg:color7 bg:color1"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:color2"
format = '[ $symbol $branch ](fg:matugen-color7 bg:color2)'

[git_status]
style = "bg:color6"
format = '[($all_status$ahead_behind )](fg:matugen-color7 bg:color2)'

[nodejs]
symbol = ""
style = "bg:color11"
format = '[[ $symbol ($version) ](fg:matugen-color7 bg:color2)]($style)'

[rust]
symbol = ""
style = "bg:color11"
format = '[[ $symbol ($version) ](fg:matugen-color7 bg:color2)]($style)'

[golang]
symbol = ""
style = "bg:color11"
format = '[[ $symbol ($version) ](fg:matugen-color7 bg:color2)]($style)'

[php]
symbol = ""
style = "bg:color11"
format = '[[ $symbol ($version) ](fg:matugen-color7 bg:color2)]($style)'

[conda]
symbol = " "
style = "bg:color12"
format = '[ $symbol$environment ](fg:#a0a9cb bg:color12)'
ignore_base = false

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:color12"
format = '[[  $time ](fg:#a0a9cb bg:color12)]($style)'

