# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#f0dfd6"

# Title color for boxes
theme[title]="#ffb782"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#c7ca95"

# Background color of selected item in processes box
theme[selected_bg]="#ffb782"

# Foreground color of selected item in processes box
theme[selected_fg]="#4f2500"

# Color of inactive/disabled text
theme[inactive_fg]="#d6c3b7"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#ffb782"

# Cpu box outline color
theme[cpu_box]="#ffb4ab"

# Memory/disks box outline color
theme[mem_box]="#ff891b"

# Net up/down box outline color
theme[net_box]="#5e78dd"

# Processes box outline color
theme[proc_box]="#9f8d83"

# Box divider line and small boxes line color
theme[div_line]="#52443b"

# Temperature graph colors
theme[temp_start]="#5edd73"
theme[temp_mid]="#dfc450"
theme[temp_end]="#e67a67"

# CPU graph colors
theme[cpu_start]="#00bcd4"
theme[cpu_mid]="#d4d400"
theme[cpu_end]="#ff0040"

# Mem/Disk free meter
theme[free_start]="#e4bfa7"
theme[free_mid]="#e4bfa7"
theme[free_end]="#5b412f"

# Mem/Disk cached meter
theme[cached_start]="#c7ca95"
theme[cached_mid]=""
theme[cached_end]="#464920"

# Mem/Disk available meter
theme[available_start]="#ffb782"
theme[available_mid]=""
theme[available_end]="#6d390a"

# Mem/Disk used meter
theme[used_start]="#ff0040"
theme[used_mid]="#ff2060"
theme[used_end]="#ff4080"

# Download graph colors
theme[download_start]="#e4bfa7"
theme[download_mid]="#ffb782"
theme[download_end]="#c7ca95"

# Upload graph colors
theme[upload_start]="#4f88df"
theme[upload_mid]="#c9b147"
theme[upload_end]="#d15656"