check_contrast = true 
# saturation = 0

#
# palette = "light"
backend="wal"

color_space = "lch"

[templates]


vscode = { src = 'vscode.json', dst = '~/.cache/wallust/colors.json' }
vscode2 = { src = 'vscode', dst = '~/.cache/wallust/colors' }
waybar = { src = 'waybar.css', dst = '~/.config/waybar/colors-waybar.css'}
kitty = { src='kitty.conf', dst='~/.cache/wallust/colors-kitty.conf'}
zen = { src='zen.json', dst='~/.cache/wal/colors.json'}
neovim = { src = 'colors_neopywal.vim', dst='~/.cache/wallust/colors_neopywal.vim'}
rofi = { src = 'rofi-colors.rasi', dst ='~/.config/rofi/colors/colors-wallust.rasi'}
shell = { src = 'colors.sh', dst = '~/.cache/wallust/colors.sh'}
