"$schema" = 'https://starship.rs/config-schema.json'

format = '''
[](primary)$os$username[](fg:primary) [](secondary)$directory[](fg:secondary)$git_branch$git_status$nodejs$rust$golang$php$python$cmd_duration
$character'''

palette = 'colors'

[palettes.colors]
primary = '#aec6ff'
on_primary = '#122f60'
secondary = '#bfc6dc'
on_secondary = '#293041'
tertiary = '#dfbbde'
on_tertiary = '#402843'
surface_container = '#282a2f'
on_surface = '#e2e2e9'
err = '#ffb4ab'

[os]
disabled = false
style = "fg:on_primary bg:primary"
format = "[$symbol ]($style)"

[os.symbols]
Arch = "󰣇"

[username]
show_always = true
style_user = "fg:on_primary bg:primary"
style_root = "fg:on_primary bg:primary bold"
format = "[$user]($style)"

[directory]
style = "fg:on_secondary bg:secondary"
format = "[$path]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "fg:on_tertiary bg:tertiary"
format = ' [](fg:tertiary)[$symbol $branch]($style)'

[git_status]
style = "fg:on_tertiary bg:tertiary"
format = '[( $all_status$ahead_behind)]($style)[](fg:tertiary)'

[nodejs]
symbol = ""
style = "fg:on_surface bg:surface_container"
format = ' [](fg:surface_container)[$symbol ($version)]($style)[](fg:surface_container)'

[rust]
symbol = ""
style = "fg:on_surface bg:surface_container"
format = ' [](fg:surface_container)[$symbol ($version)]($style)[](fg:surface_container)'

[golang]
symbol = ""
style = "fg:on_surface bg:surface_container"
format = ' [](fg:surface_container)[$symbol ($version)]($style)[](fg:surface_container)'

[php]
symbol = ""
style = "fg:on_surface bg:surface_container"
format = ' [](fg:surface_container)[$symbol ($version)]($style)[](fg:surface_container)'

[python]
symbol = ""
style = "fg:on_surface bg:surface_container"
format = ' [](fg:surface_container)[$symbol ($version)]($style)[](fg:surface_container)'

[cmd_duration]
min_time = 2000
style = "fg:on_surface bg:surface_container"
format = ' [](fg:surface_container)[󱎫 $duration]($style)[](fg:surface_container)'

[character]
success_symbol = '[❯](bold fg:primary)'
error_symbol = '[❯](bold fg:err)'
