cursor #f0dfd6
cursor_text_color #d6c3b7

foreground            #f0dfd6
# background            #141414
selection_foreground  #422b1a
selection_background  #e4bfa7
url_color             #ffb782

# black
# color8   #585252
# color0   #4c4c4c

# red
color1   #b8545b
color9   #b15b5f

# green
color2   #ffb782
color10  #ffb782

# yellowwa
color3   #b1aa63
color11  #beb769

# blue
/* color4  #776dafff */
color4  #ffb782
color12 #a39ec4

# magenta
color5   #ac8aac
color13  #c49ec4

# cyan
color6   #8aacab
color14  #9ec3c4

# white
color15   #e7e7e7
color7  #f0f0f0
